---
- name: Installing software specific to Debian OS
  include: debian.yml
  when: ansible_os_family == 'Debian'

- name: Installing software specific to Arch Linux OS
  include: archlinux.yml
  when: ansible_os_family == 'Archlinux'
