---
- name: Fetch oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
- name: Fetch dotfiles
  git: repo=http://github.com/Burmudar/dotfiles dest={{ tools_path }}/dotfiles force=yes
- name: Link vimrc
  shell: stow -t {{ home_path }} vim chdir={{ tools_path }}/dotfiles/ 
  ignore_errors: yes
- name: Link zshrc
  shell: stow -t {{ home_path }} zsh chdir={{ tools_path }}/dotfiles/
  ignore_errors: yes
- name: Check if shell is ZSH
  command: 'echo $SHELL'
  register: shell
- name: Change default shell to ZSH
  command: chsh -s /bin/zsh
  when: shell.stdout.find('/bin/zsh') == -1
