---
- hosts: localhost
  user: william
  connection: local
  sudo: true
  vars:
    home_path: "/home/william/"
    programming_path: "{{ home_path }}/programming"
    tools_path: "{{ programming_path }}/tools"
  pre_tasks:
  - name: create programming directory
    file: path={{ programming_path }} state=directory
  - name: create tools directory
    file: path={{ tools_path }} state=directory
  roles:
    - software
    - tools
    - config
