---
- hosts: localhost
  user: williambezuidenhout
  connection: local
  pre_tasks:
  - name: Include OS specific vars
    include_vars: "{{ item }}"
    with_first_found:
      - "vars/{{ ansible_os_family|lower }}.yml"
      - vars/linux.yml
  - name: OS specific pre task
    include: "{{ item }}"
    with_first_found:
      - "tasks/{{ ansible_os_family|lower }}.yml"
      - tasks/default.yml
  roles:
    - software
    - tools
    - config
